### ISSUE TITLE
New Design, Header Site

### ISSUE THREAD

**Issue by JonDotsoy** [Otecnya/core#2]
Is required a new header site. More websites have impact by a specific slogan, Such that it can define the business in the first time.

To it require:
 - [x] A simple style (Only slogan). #3 
 - [x] Slogan defined. #4

**Comment by josecaamano** [comment]
Nicolas Gonzalez Granic 
Gerente Comercial


José Caamaño Gonzalez 
Gerente de Operaciones

**Comment by JonDotsoy** [comment]
![image](https://cloud.githubusercontent.com/assets/3086539/19011173/d22e745c-8764-11e6-915c-11ec770c65c5.png)
