### ISSUE TITLE
The Header with a simple style

### ISSUE THREAD

**Issue by JonDotsoy** [Otecnya/core#3]
The design at presentatión by slogan.

This only to watch.
 - Big Slogan
 - Head logo

![design header](https://cloud.githubusercontent.com/assets/3086539/18792473/178c7432-818d-11e6-9e64-93e40ee07945.png)

**Comment by JonDotsoy** [comment]
Captura Avance **2016-09-26 05_49_12**

![image](https://cloud.githubusercontent.com/assets/3086539/18828170/fc43de8c-83ac-11e6-9721-e5c918e34f0a.png)

**Comment by JonDotsoy** [comment]
![image](https://cloud.githubusercontent.com/assets/3086539/18829366/4dec50a2-83b2-11e6-9efd-595ef70b39a4.png)

**Comment by josecaamano** [comment]
EN  OTECNYA CREAMOS SOLUCUONES 

CONTACTANOS

**Comment by JonDotsoy** [comment]
El diseño para el nuevo header quedaría así.

![image](https://cloud.githubusercontent.com/assets/3086539/18851230/596985c6-8411-11e6-8954-982fc3d08887.png)

**Comment by josecaamano** [comment]
Ok 

Jonathan la palabra es contáctanos,,

Esta súper bien 

José Caamaño G.
Gerente de Operaciones 
+56 9 82705229
www.otecnya.cl

**Comment by JonDotsoy** [comment]
Vista previa http://104.131.86.197:13000/
