### ISSUE TITLE
New clients 🗣

### ISSUE THREAD

**Issue by JonDotsoy** [Otecnya/core#5]
What are new clients? — Define on the next format:

 - Name
 - URL
 - Description ***(Optional)***

**Comment by josecaamano** [comment]
Linsa
Tramaca
Reserva 
Viggo
Achs

**Comment by JonDotsoy** [comment]
Esto es correcto? @josecaamano 

- Linsa — http://www.linsa.cl/
- Tramaca — http://www.tramaca.cl/
- Reserva — http://www.reserva.cl/
- Viggo — http://www.viggo.cl/
- Achs — http://www.achs.cl/

**Comment by JonDotsoy** [comment]
@josecaamano los logos representativos de cada empresa. La solicitare en un formato preferencial para cada empresa. Ya que no todas las empresas tienen images que se pueden presentar correctamente en este formato. 

![image](https://cloud.githubusercontent.com/assets/3086539/18850774/5c4381b8-840f-11e6-9679-64dfc9f37d8a.png)

¿Que opinas, eliminó a las marcas sin formato correcto?
