### ISSUE TITLE
Design Site (Map Site)

### ISSUE THREAD

**Issue by JonDotsoy** [Otecnya/core#6]
It is proposition of site. The structure of the site, how the user searching the data.

![image](https://cloud.githubusercontent.com/assets/3086539/18847702/98df0894-8401-11e6-9d5c-d9f801dcd3d5.png)

**Comment by JonDotsoy** [comment]
@josecaamano que agregar en el home del sitio. Ahora solo existe el simulador.

**Comment by JonDotsoy** [comment]
Se ha integrado la sección "AboutUs" http://104.131.86.197:13000/aboutus echale un vistaso.

**Comment by josecaamano** [comment]
Jonathan:

 

Podemos colocar fotos más formales e incluir la coordinadora, 

 

Pero está quedando buenísima, utiliza los cursos que te envié en presentación de la otec en Word, 

 

Atte. 

 

 

 

José Caamaño G.

Gerente de Operaciones

Cel:  <tel:%2B56%209%2082705229> +56 9 82705229

Fijo: 022 8146409

Nueva Providencia 1881 Of 2308

 <http://www.otecnya.cl/> www.otecnya.cl



 

 

De: Jon Dotsoy [mailto:notifications@github.com] 
Enviado el: miércoles, 28 de septiembre de 2016 11:48
Para: Otecnya/core <core@noreply.github.com>
CC: josecaamano <j.caamano@otecnya.cl>; Mention <mention@noreply.github.com>
Asunto: Re: [Otecnya/core] Design Site (Map Site) (#6)

 

Se ha integrado la sección "AboutUs" http://104.131.86.197:13000/aboutus echale un vistaso.
